[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/save-lead"
  to = "/.netlify/functions/save-lead"
  status = 200

[[redirects]]
  from = "/api/create-order"
  to = "/.netlify/functions/create-order"
  status = 200

[[redirects]]
  from = "/api/verify-payment"
  to = "/.netlify/functions/verify-payment"
  status = 200

[[redirects]]
  from = "/api/admin-auth"
  to = "/.netlify/functions/admin-auth"
  status = 200
